[package]
name = "liste"
version = "0.0.1"
authors = ["poulp <amathieu@protonmail.com>"]
description = "RSS reader for terminal with rust and ncurses"
license = "WTFPL"

[dependencies]
ncurses = "5.85.0"
feed = "2.1.0"
clap = "2.24.1"
